site_name: HaCRoM Documentation 
theme: readthedocs
plugins:
    - search

markdown_extensions:
        - smarty
        - toc:
              permalink: True
        - sane_lists

pages:
    - Home : 'index.md'
